service: example-go-app

provider:
  name: aws
  runtime: go1.x
  region: eu-west-1
  environment:
    EPSAGON_TOKEN: ${env:EPSAGON_TOKEN}

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  hello:
    handler: main
  events:
    - http:
        path: hello
        method: post
